### PR TITLE
get_h5py_file

### PR DESCRIPTION
**Pull request by luiztauffer**
Auxiliary method to easily convert from InputFile to SI recording, presuming the reference is a remote NWB file.
It could be used in a Processor like this:

```python
class MyProcessor(ProcessorBase):
    @staticmethod
    def run(context: MyProcessorContext):
        recording = MyProcessorContext.input_file.to_si_recording(electrical_series_path="acquisition/ElectricalSeries")
```

### CODE REVIEW

**Comment by luiztauffer** [comment]
@magland I copied the `NwbRecording` class you were using in some Processors, but I believe the ideal thing would be to use SI directly here, eventually

**Comment by luiztauffer** [comment]
thinking about it now, it could be useful to also have a `InputFile.to_nwbfile()` method

**Comment by magland** [comment]
@luiztauffer there are three main differences between this version of NwbRecording and the one in SI, and reasons we shouldn't switch over yet. (1) It's simpler and more malleable since we'll want to have control over exactly how it does the reading. (2) it uses remfile instead of fsspec, which I believe makes it much more efficient for reading (3) it uses h5py file rather than pynwb, because I found the latter to have a lot of overhead in terms of loading time and is less flexible.

For reason (3) I think we should hold off on the to_nwbfile() idea, until we get to a point where we really want to use pynwb.

@alejoe91

**Comment by luiztauffer** [comment]
@magland 
I see, I'm fine with using a custom implementation for now. In the way I arranged it, it will be easy to change in the future if those options become available on SI

**Comment by magland** [comment]
@luiztauffer so I didn't reaize this was in the dendro repo. I don't think SI or spike sorting functionality should be in dendro Python. I'm thinking of it as a much more general tool.

The exception being that the frontend has spike-sorting-specific stuff... I think that's okay for now since at this point we are targeting a very specific user experience in the GUI.

**Comment by luiztauffer** [comment]
@magland 
My thinking here is that, if we’ll be using `dendro.InputFile` class as the main interface with remote files (mainly NWB for now), it would make sense to have builtin utility methods for the most common read operations and most common neurophysiology packages, so we don’t have to repeat ourselves in the Processors code.

In this way we can avoid maintaining code like this repeated throughout multiple Processors:
```python
import h5py
import spikeinterface as si
import remfile
from NwbRecording import NwbRecording

input = context.input

# open the remote file
remf = remfile.File(input) # input has a get_url() method which will auto-renew the signed download url if it has expired
f = h5py.File(remf, 'r')

recording = NwbRecording(
    file=f,
    electrical_series_path=context.electrical_series_path
)
```

I agree Dendro SDK barebones should not be dependent on SpikeInterface, but we can make this dependency optional, e.g. `pip install dendo[spikeinterface]`, and only processors using SI (we’ll have many of them) would need to install like that.

**Comment by magland** [comment]
I think it's okay to repeat that code because it is better to be explicit about what is happening. I am concerned about implicitly depending on spikeinterface for operations that are happening in the protocaas sdk. We'll usually want a processor to depend on a specific version of spikeinterface - I don't think we want to worry about whether that version is compatible with protocaas sdk.

There are other ways to reduce duplicating that code without having protocaas depend on spikeinterface. For example we could have protocaas implement get_h5py_file()

```python
from NwbRecording import NwbRecording

input = context.input

recording = NwbRecording(
    file=input.get_h5py_file(),
    electrical_series_path=context.electrical_series_path
)
```

I view NwbRecording as something that will certainly change, but that we'll also want processors to depend on very specific implementations of that - so that they don't break if a new image is built with the latest protocaas sdk.

**Comment by luiztauffer** [comment]
> For example we could have protocaas implement get_h5py_file()

fair enough, I'll change the code to incorporate that method and we'll leave out the dependency on SI

**Pull request merged**
