### PR TITLE
Manage dashboard with css grid

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR introduces the use of CSS Grid to handle the sizing of nav, sidebar, and main elements in the application.

At this moment, the `Splitter.tsx` component cannot be adjusted since this heavily relied on explicit height / width declarations—though this should be the only inconsistency.

@magland Thought I'd share this, though I'll keep it in draft mode until the former issue is resolved. Can you peruse to see if anything else looks wonky? Not all of my tables and other components are populated, which may bias my tests.

### CODE REVIEW

**Comment by magland** [comment]
Overall looks good. You removed `W` and `H` in TabWidget.tsx and so this is causing the page to crash for me.

TabWidget is going to be another component that you'll have trouble with in this overhaul.

**Comment by magland** [comment]
@garrettmflynn I updated this branch to reflect the new name (protocaas -> dendro).

I'm going to look into getting splitter and tab widgets to work.

**Comment by magland** [comment]
@garrettmflynn I played around with this a bit and I'm not sure how I can accomplish the nested splitter widgets without passing explicit sizes down to the child windows. The issue is that you could have splitters nested within tab widgets nested within other splitters, and it's difficult to have the flexibility of controlling the behavior. Also, there could eventually be widgets that require knowing their width/height in order to display properly. Not sure if there are mechanisms for handling this using css strategy.

**Comment by garrettmflynn** [comment]
No worries, there may be strategies—but they'll likely be equally contrived if we're trying to maintain the exact same rendering behaviors in an existing system.

You can close this PR and I'll find a simpler solution to the scroll issue. More than anything, just wanted to put these CSS strategies on your radar.

**Pull request closed without merging**
