### PR TITLE
pypi release action

### PR DESCRIPTION
**Pull request by luiztauffer**
Action workflow to auto build and publish PyPI package - needs testing

### CODE REVIEW

**Comment by magland** [comment]
@luiztauffer When does this get triggered? Doesn't seem like it should publish on every push.

**Comment by luiztauffer** [comment]
```
on:
  push:
    branches:
      - main
    paths:
      - python/**
```

this mean it will be triggered every time changes happen inside the `python/` dir in the `main` branch

**Comment by magland** [comment]
> ```
> on:
>   push:
>     branches:
>       - main
>     paths:
>       - python/**
> ```
> 
> this mean it will be triggered every time changes happen inside the `python/` dir in the `main` branch

But do we want to publish on every python change? Is the idea that it won't actually create a new release unless the version changes in setup.py?

**Comment by luiztauffer** [comment]
I think we should keep the PyPI version in line with the code version in `main`, this is a good practice
Yes, the publishing will only finalize successfully if we update the version inside `setup.py`

**Pull request merged**
